//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TANOR_project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderID { get; set; }
        public string OrderDescription { get; set; }
        public byte[] OrderImage { get; set; }
        public int UserID { get; set; }
        public bool Status { get; set; }
        public bool ConfirmedOrderStatus { get; set; }
    
        public virtual User User { get; set; }
    }
}
